# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
commands:
  my-command:
    steps:
      - run: echo "Upgarde AGW & FEG, Magma nodes"
      - run: echo "Fetching latest version from APT-Cache"
jobs:
  get_version:
    machine:
      image: ubuntu-1604:201903-01
      
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:71:38:2c:70:cb:fc:6d:e9:9a:b6:61:0d:c5:b7:5a"
      - run:
          name: "get latest version"
          command:  |
            ssh magma@192.168.61.17"cd /home/magma/terravm_logs && sh get_version.sh > version.txt"
          
      - run:
          name: "upload version scriipit in ng40"
          command: scp version.txt magma@192.168.60.109:/home/magma   


workflows:
  version: 2
  alltest:
    jobs:
      - get_version
